DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS vibes;
CREATE TABLE vibes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid_1 INTEGER NOT NULL,
  uid_2 INTEGER NOT NULL,
  token TEXT NOT NULL,
  verified BOOLEAN NOT NULL CHECK (verified IN (0, 1)),
  signature TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


DROP TABLE IF EXISTS vibes_summary;
CREATE TABLE vibes_summary (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uid_1 INTEGER NOT NULL,
  uid_2 INTEGER NOT NULL,
  count INTEGER NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
